module.exports = {
    name: "spam_dm",
    category: "nuke",
    permissions: [],
    devOnly: true,
    run: async ({client, message, args}) => {
        mentiondm = message.mentions.users.first();
        if(mentiondm){
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
            mentionMessage = message.content.slice(27)
            mentiondm.send(mentionMessage)
        }
    }
}