module.exports = {
    name: "spam",
    category: "nuke",
    permissions: [],
    devOnly: true,
    run: async ({client, message, args}) => {
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
        message.channel.send("@everyone")
    }
}